FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src

COPY ["TimesUp.csproj", "./"]
RUN dotnet restore -r linux-arm "TimesUp.csproj"
COPY . .

WORKDIR "/src/."
RUN dotnet publish "TimesUp.csproj" -c Release -o /app/publish -r linux-arm --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim-arm32v7
WORKDIR /app
EXPOSE 80
EXPOSE 443

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "TimesUp.dll"]
