name: CI to Docker Hub

on:
  push:
    branches: [ master, enhancement/dotnet6 ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Infer Docker tag from branch name
        shell: bash
        run: echo "##[set-output name=tag;]$(echo `[[ ${{ steps.extract_branch.outputs.branch }} = master ]] && latest || sed 's/\//_/g' ${{ steps.extract_branch.outputs.branch }}`)"
        id: extract_tag
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: pecomare/timesup:${{ steps.extract_tag.outputs.tag }}
          platforms: linux/amd64, linux/arm64, linux/arm/v7